[package]
name = "todo_queue_app"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.3", features = ["derive"] }
clap = { version = "4.5.23", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
dialoguer = "0.12.0"
